### ISSUE TITLE
Deprecation warning in console for Firefox detection method

### ISSUE THREAD

**Issue by gilmoreorless** [RickyRomero/shut-up-webextension#40]
The `webBrowser` helper is using the following check for Firefox:

```js
if (typeof InstallTrigger !== 'undefined') {
  return 'Firefox'
}
```

However, `InstallTrigger` and related APIs were deprecated in Firefox 100: https://bugzilla.mozilla.org/show_bug.cgi?id=1754441
This means that each page loaded in Firefox with this extension active puts a warning in the devtools console:
```
InstallTrigger is deprecated and will be removed in the future.
```

From reading some related bug reports, it looks like the Firefox team wanted to quickly remove an API only used for external installing of extensions. But they've since realised that it's a very commonly-used way to detect Firefox:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1804302#c11
* https://bugzilla.mozilla.org/show_bug.cgi?id=1776423#c2
* https://bugzilla.mozilla.org/show_bug.cgi?id=1774005#c1

I tested the future behaviour by setting `extensions.InstallTrigger.enabled` to `false` in `about:config`, and this extension _appears_ to still work correctly. I didn't test everything though, and I noticed it switches to injecting the base64 data URI instead of a `moz-extension://` stylesheet.

**Comment by RickyRomero** [comment]
Hey @gilmoreorless, thank you for going above and beyond with this detailed bug report. Sounds like a pretty easy thing to fix – I need a new way to detect Firefox in that abstraction. I'll update this issue when I have a solution.

By the way:

> I noticed it switches to injecting the base64 data URI instead of a `moz-extension://` stylesheet.

If you're curious about why this happens, Shut Up has a stylesheet update mechanism it uses on other browsers. It caches that stylesheet locally and uses base64 to add it to the page. However, Firefox's add-on gallery prohibits remotely-hosted code, so I disable the updater code path using this (now deprecated) test, opting to directly embed the resource from the extension bundle instead. I'll need to update this test to remain compliant with Mozilla's policies. 😅

**Comment by RickyRomero** [comment]
Hello again! The upcoming 8.1 update doesn't use this platform detection technique anymore, so it should solve the problem. I'll have that out later this month. Thanks again for the bug report.
